# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beac9c10b557ca715ebcecfa274b17d74fb61863e4d7a27300807506ef77a5745a659d6c41cc1a47ac872476b3684468e19952f09108b2643bff5175b594a486

test:
  secret_key_base: a53fd2cb982a5f05a5bfe0bd37c4abc9e9782534f577b52dbab0337772fda0b042800e1c763c09dcdca81b5fffbe57f3a2ba930f689e104ea788814b03423113

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
